# Cloudflare Worker configuration for RSS feed refresh queue
name = "rss-refresh-consumer"
main = "cloudflare-workers/queue-consumer-worker.js"
compatibility_date = "2024-01-15"

# Queue consumer configuration
[[queues.consumers]]
queue = "refresh-feed"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "refresh-feed-dlq"

# Environment variables
[env.production]
name = "rss-refresh-consumer"

[env.development]
name = "rss-refresh-consumer-dev"

# KV namespaces for storing queue results (optional) - commented out for now
# [[kv_namespaces]]
# binding = "QUEUE_RESULTS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# KV namespace for batch status tracking (SSE)
[[kv_namespaces]]
binding = "BATCH_STATUS"
id = "32dfe3986c4640a9a7eb5a7376812483"
preview_id = "77db1cfa35814f73b10cec6dce9db940"

# Durable Object for real-time batch status (ELIMINATES POLLING!)
[durable_objects]
bindings = [
  { name = "BATCH_STATUS_DO", class_name = "BatchStatusDurableObject", script_name = "batch-status-manager" }
]

# Variables
[vars]
ENVIRONMENT = "production"
PAGES_FUNCTION_URL = "https://socialnetworksandbox.com"
PAGES_FUNCTION_TOKEN = ""

# Pages compatibility for Durable Objects
[env.production.durable_objects]
bindings = [
  { name = "BATCH_STATUS_DO", class_name = "BatchStatusDurableObject", script_name = "batch-status-manager" }
] 