import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import "./ios-chrome-fixes.css";
import { ConvexAuthNextjsServerProvider, convexAuthNextjsToken } from "@convex-dev/auth/nextjs/server";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { UserMenuServer, getUserProfile } from "@/components/user-menu/UserMenuServer";
import { AudioProvider } from "@/components/audio-player/AudioContext";
import { PersistentPlayer } from "@/components/audio-player/PersistentPlayer";
import { MobileDock } from "@/components/ui/mobile-dock";
import { SidebarProvider } from "@/components/ui/sidebar-context";
import { Inter, JetBrains_Mono } from "next/font/google";
import { ViewportHandler } from "@/components/ui/ViewportHandler";
import { SafeAreaHandler } from "@/components/ui/SafeAreaHandler";
import { IOSDetector } from "@/components/ui/IOSDetector";


const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Convex + Next.js + Convex Auth",
  description: "Generated by npm create convex",
  icons: {
    icon: "/convex.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get all user profile information
  const { displayName, isAuthenticated, isBoarded, profileImage, userId, pendingFriendRequestCount } = await getUserProfile();

  return (
    <ConvexAuthNextjsServerProvider>
      {/* `suppressHydrationWarning` only affects the html tag,
      // and is needed by `ThemeProvider` which sets the theme
      // class attribute on it */}
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover, maximum-scale=1, user-scalable=no"/>
          <style dangerouslySetInnerHTML={{
            __html: `
              :root {
                --vh: 1vh;
              }
              @supports (height: 100dvh) {
                body, html {
                  height: 100dvh;
                }
              }
              /* Fix for iOS Chrome bottom bar */
              @supports (-webkit-touch-callout: none) {
                body {
                  height: 100%;
                  position: fixed;
                  width: 100%;
                  overflow: auto;
                  -webkit-overflow-scrolling: touch;
                }
              }
            `
          }} />
        </head>
        <body
          className={`${inter.variable} ${jetbrainsMono.variable} antialiased no-overscroll h-screen ios-chrome-fix`}
        >
          <ConvexClientProvider>
            <ThemeProvider attribute="class">
              <AudioProvider>
                <SidebarProvider 
                  isAuthenticated={isAuthenticated} 
                  username={displayName}
                  displayName={displayName}
                  isBoarded={isBoarded}
                  profileImage={profileImage}
                  userId={userId}
                  pendingFriendRequestCount={pendingFriendRequestCount}
                >
                  <IOSDetector />
                  <ViewportHandler />
                  <SafeAreaHandler />
                  <div className="min-h-screen flex flex-col ios-chrome-fix">
                    <div className="hidden">
                      <UserMenuServer />
                    </div>
                    {children}
                  </div>
                  <PersistentPlayer />
                  <MobileDock />
                </SidebarProvider>
              </AudioProvider>
            </ThemeProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
